services:
  runner:
    container_name: runner
    image: commontorizon/torizon-yocto-github-runner-dev:6.7.0
    environment:
      - REPO=commontorizon/commontorizon-manifest
      - ACCESS_TOKEN=${ACCESS_TOKEN}
    volumes:
      - "$PWD:/workdir"
      - "$OSTREE_REPO:/ostree"
    working_dir: /workdir
    command:
      - start.sh
